# -*- mode: python ; coding: utf-8 -*-
import sys
import os

icon_path = os.path.join(SPECPATH, 'app_icon.ico')

block_cipher = None

a = Analysis(
    ['auto_screenshot.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pyautogui',
        'pygetwindow',
        'keyboard',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'cv2',
        'pandas',
        'scipy',
        'matplotlib',
        'IPython',
        'jupyter',
        'notebook',
        'sphinx',
        'pytest',
        'test',
        'tests',
        'email',
        'html',
        'xml',
        'xmlrpc',
        'multiprocessing',
        'sqlite3',
        'tkinter.test',
        'pydoc',
        'distutils',
        'setuptools',
        'pkg_resources',
        'numpy.testing',
        'numpy.distutils',
        'numpy.f2py',
        'numpy.fft',
        'numpy.polynomial',
        'numpy.random._examples',
        'PIL.FpxImagePlugin',
        'PIL.MicImagePlugin',
        'PIL.SgiImagePlugin',
        'PIL.FliImagePlugin',
        'PIL.McIdasImagePlugin',
        'PIL.TgaImagePlugin',
        'PIL.WalImageFile',
        'PIL.XVThumbImagePlugin',
        'PIL.IptcImagePlugin',
        'PIL.ImImagePlugin',
        'PIL.MpoImagePlugin',
        'PIL.SpiderImagePlugin',
        'PIL.MpegImagePlugin',
        'PIL.DcxImagePlugin',
        'PIL.EpsImagePlugin',
        'PIL.GbrImagePlugin',
        'PIL.PixarImagePlugin',
        'PIL.PsdImagePlugin',
        'PIL.SunImagePlugin',
        'PIL.XpmImagePlugin',
        'PIL.BufrStubImagePlugin',
        'PIL.FitsImagePlugin',
        'PIL.GribStubImagePlugin',
        'PIL.Hdf5StubImagePlugin',
        'PIL.IcoImagePlugin',
        'PIL.Jpeg2KImagePlugin',
        'PIL.PalmImagePlugin',
        'PIL.PcxImagePlugin',
        'PIL.PdfImagePlugin',
        'PIL.XbmImagePlugin',
        'mouseinfo',
        'pyperclip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='终末地截图工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
    icon=icon_path,
)
